# Generated by Django 5.2.10 on 2026-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('strength', 'Fuerza'), ('cardio', 'Cardio'), ('flexibility', 'Flexibilidad'), ('full_body', 'Cuerpo Completo')], max_length=20, verbose_name='Categoría')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20, verbose_name='Dificultad')),
                ('benefits', models.TextField(blank=True, verbose_name='Beneficios')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['category', 'difficulty', 'name'],
            },
        ),
    ]
