# Generated by Django 5.0.6 on 2026-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, help_text='Calorías aproximadas quemadas', null=True, verbose_name='Calorías quemadas'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada del ejercicio en minutos', null=True, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instrucciones detalladas para realizar el ejercicio correctamente', verbose_name='Instrucciones paso a paso'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube o Vimeo', verbose_name='URL del video'),
        ),
    ]
