# Generated by Django 5.2.10 on 2026-02-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_workoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='common_mistakes',
            field=models.TextField(blank=True, help_text='Errores frecuentes a evitar y cómo corregirlos', verbose_name='Errores comunes'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles_targeted',
            field=models.TextField(blank=True, help_text='Lista de músculos principales y secundarios trabajados', verbose_name='Músculos trabajados'),
        ),
    ]
