# Generated by Django 5.2.10 on 2026-02-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercise_common_mistakes_exercise_muscles_targeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, help_text='Equipo necesario, separado por comas (ej: Kettlebell, esterilla)', max_length=200, verbose_name='Equipo necesario'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='precautions',
            field=models.TextField(blank=True, help_text='Precauciones, contraindicaciones y señales de alarma', verbose_name='Precauciones'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='progressions',
            field=models.TextField(blank=True, help_text='Cómo progresar o simplificar el ejercicio', verbose_name='Progresiones y regresiones'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='setup_tips',
            field=models.TextField(blank=True, help_text='Consejos para colocación, agarre y preparación', verbose_name='Consejos de preparación'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='variations',
            field=models.TextField(blank=True, help_text='Variantes o alternativas del ejercicio', verbose_name='Variaciones'),
        ),
    ]
