# Generated by Django 5.2.10 on 2026-07-10 23:29

from django.conf import settings
from django.db import migrations, models


def null_images_to_empty(apps, schema_editor):
    # El campo image pasa a NOT NULL; los NULL heredados del ImageField deben
    # convertirse en '' antes del AlterField.
    Exercise = apps.get_model('exercises', 'Exercise')
    Exercise.objects.filter(image__isnull=True).update(image='')


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_base_workouts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(null_images_to_empty, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Fuerza'), ('cardio', 'Cardio'), ('flexibility', 'Flexibilidad'), ('full_body', 'Cuerpo Completo')], db_index=True, max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], db_index=True, max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Nombre de archivo dentro de exercises/static/exercises/img/catalog/ (ej: kettlebell_swing.jpg)', max_length=200, verbose_name='Imagen'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique_user_exercise_favorite'),
        ),
    ]
