# Generated by Django 5.2.10 on 2026-07-11 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_image_paths_to_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración real (minutos)'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='kettlebell_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Peso de kettlebell (kg)'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Esfuerzo percibido (RPE 1-10)'),
        ),
    ]
