# Generated by Django 5.2.10 on 2026-07-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_workoutlog_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel')),
                ('goal', models.CharField(choices=[('strength', 'Ganar fuerza'), ('fat_loss', 'Perder grasa'), ('mobility', 'Movilidad y flexibilidad'), ('general', 'Acondicionamiento general')], default='general', max_length=20, verbose_name='Objetivo')),
                ('available_weights', models.CharField(blank=True, default='', help_text='Separadas por comas, ej: 8, 12, 16', max_length=100, verbose_name='Kettlebells disponibles (kg)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
