# Generated by Django 5.2.10 on 2026-08-20 03:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_push_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='client_session_id',
            field=models.UUIDField(blank=True, help_text='Evita duplicar una sesión cuando el navegador reintenta el guardado.', null=True, verbose_name='Identificador de sesión del cliente'),
        ),
        migrations.CreateModel(
            name='ExercisePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True, verbose_name='Completado')),
                ('sets_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Series completadas')),
                ('reps_completed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Repeticiones completadas')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('200'))], verbose_name='Peso usado (kg)')),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE del ejercicio')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_logs', to='exercises.exercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_performances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('workout_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='exercises.workoutexercise', verbose_name='Ejercicio de la rutina')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_performances', to='exercises.workoutlog', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Rendimiento por ejercicio',
                'verbose_name_plural': 'Rendimientos por ejercicio',
                'ordering': ['-workout_log__completed_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'exercise', '-created_at'], name='exercises_e_user_id_d6d48b_idx'), models.Index(fields=['workout_log', 'exercise'], name='exercises_e_workout_020126_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='exerciseperformance',
            constraint=models.UniqueConstraint(condition=models.Q(('workout_exercise__isnull', False)), fields=('workout_log', 'workout_exercise'), name='unique_performance_per_workout_exercise'),
        ),
    ]
