# Generated by Django 5.2.10 on 2026-08-20 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_workoutlog_client_session_id_exerciseperformance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutlog',
            constraint=models.UniqueConstraint(condition=models.Q(('client_session_id__isnull', False)), fields=('user', 'client_session_id'), name='unique_user_client_session'),
        ),
    ]
