# Generated by Django 5.2.10 on 2026-08-20 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_history_snapshots(apps, schema_editor):
    WorkoutLog = apps.get_model('exercises', 'WorkoutLog')
    ExercisePerformance = apps.get_model('exercises', 'ExercisePerformance')

    for log in WorkoutLog.objects.select_related('workout').iterator():
        workout = log.workout
        if workout is None:
            continue
        WorkoutLog.objects.filter(pk=log.pk).update(
            workout_title_snapshot=workout.title,
            workout_difficulty_snapshot=workout.difficulty,
            workout_duration_snapshot=workout.estimated_duration,
        )

    for performance in ExercisePerformance.objects.select_related('exercise', 'workout_exercise').iterator():
        exercise = performance.exercise
        workout_exercise = performance.workout_exercise
        ExercisePerformance.objects.filter(pk=performance.pk).update(
            exercise_name_snapshot=exercise.name if exercise else '',
            exercise_category_snapshot=exercise.category if exercise else '',
            target_sets=workout_exercise.sets if workout_exercise else None,
            target_reps=workout_exercise.reps if workout_exercise else '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_workoutlog_unique_user_client_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseperformance',
            name='exercise_category_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exerciseperformance',
            name='exercise_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exerciseperformance',
            name='target_reps',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exerciseperformance',
            name='target_sets',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aviso de plan descartado'),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_plan_managed',
            field=models.BooleanField(db_index=True, default=False, help_text='Las rutinas internas de un plan no se muestran en la biblioteca personal.', verbose_name='Gestionado por un plan'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_difficulty_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_duration_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.workout'),
        ),
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Orden')),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='Semana')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('focus', models.CharField(max_length=20, verbose_name='Enfoque')),
                ('session_kind', models.CharField(default='main', max_length=20, verbose_name='Tipo de sesión')),
                ('phase', models.CharField(default='base', max_length=20, verbose_name='Fase')),
                ('estimated_duration', models.PositiveSmallIntegerField(verbose_name='Duración estimada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('skipped', 'Omitida')], db_index=True, default='pending', max_length=12)),
                ('adaptation_reason', models.CharField(blank=True, default='', max_length=300, verbose_name='Motivo del ajuste')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_session', to='exercises.workout', verbose_name='Rutina generada')),
            ],
            options={
                'verbose_name': 'Sesión planificada',
                'verbose_name_plural': 'Sesiones planificadas',
                'ordering': ['scheduled_date', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='planned_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_log', to='exercises.plannedsession', verbose_name='Sesión planificada'),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('strength', 'Ganar fuerza'), ('fat_loss', 'Perder grasa'), ('mobility', 'Movilidad y flexibilidad'), ('general', 'Acondicionamiento general')], default='general', max_length=20, verbose_name='Objetivo')),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel')),
                ('sessions_per_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Sesiones por semana')),
                ('session_duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)], verbose_name='Duración de sesión (minutos)')),
                ('preferred_weekdays', models.JSONField(default=list, help_text='Lista de días ISO: 0=lunes, 6=domingo.', verbose_name='Días preferidos')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('reminders_enabled', models.BooleanField(default=False, verbose_name='Recordatorios activos')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Hora del recordatorio')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='active', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plan de entrenamiento',
                'verbose_name_plural': 'Planes de entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exercises.trainingplan', verbose_name='Plan'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['user', 'status'], name='exercises_t_user_id_1af0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['user', '-created_at'], name='exercises_t_user_id_df14ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'paused'])), fields=('user',), name='unique_open_training_plan_per_user'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['plan', 'scheduled_date', 'status'], name='exercises_p_plan_id_ac8b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['scheduled_date', 'status', 'reminder_sent_at'], name='exercises_p_schedul_c7d527_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedsession',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='unique_plan_session_sequence'),
        ),
        migrations.AddConstraint(
            model_name='plannedsession',
            constraint=models.UniqueConstraint(fields=('plan', 'scheduled_date'), name='unique_plan_session_date'),
        ),
        migrations.RunPython(backfill_history_snapshots, migrations.RunPython.noop),
    ]
