# Generated by Django 5.2.10 on 2026-08-31 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_adaptive_training_plan_and_history_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedsession',
            name='available_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)], verbose_name='Minutos disponibles'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='energy_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Muy baja'), (2, '2 - Baja'), (3, '3 - Normal'), (4, '4 - Buena'), (5, '5 - Muy buena')], null=True, verbose_name='Energía antes de entrenar'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='pain_level',
            field=models.CharField(blank=True, choices=[('none', 'Sin dolor'), ('mild', 'Molestia leve'), ('stop', 'Dolor: detener')], max_length=5, null=True, verbose_name='Dolor o molestia'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='readiness_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chequeo de preparación'),
        ),
    ]
